parameter_defaults:
  CephAnsibleDisksConfig:
    devices:
      - /dev/vdb
      - /dev/vdc
      - /dev/vdd
    osd_scenario: collocated
    journal_size: 1024
  # https://bugs.launchpad.net/tripleo/+bug/1749544
  CephPoolDefaultSize: 1
  CephPoolDefaultPgNum: 32
# CephConfigOverrides:
#   mon_max_pg_per_osd: 2048
  CephAnsiblePlaybookVerbosity: 3
  CephAnsibleEnvironmentVariables:
    ANSIBLE_SSH_RETRIES: '6'
    DEFAULT_FORKS: '2'

